# Generated by Django 4.2.6 on 2023-10-15 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="hotel",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="hotel.hotel"
            ),
            preserve_default=False,
        ),
    ]
