# Generated by Django 4.2.6 on 2023-11-26 15:24

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=40)),
                ("last_name", models.CharField(max_length=40)),
                ("middle_name", models.CharField(max_length=40)),
                ("specialization", models.CharField(max_length=40)),
                ("gender", models.CharField(max_length=40)),
                ("date_of_birth", models.DateField()),
                ("date_of_empoloyment", models.DateField()),
                ("education", models.CharField(max_length=40)),
                ("date_of_resignation", models.DateField()),
                ("contract_details", models.CharField(max_length=40)),
            ],
            options={
                "db_table": "Doctor",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=40)),
                ("last_name", models.CharField(max_length=40)),
                ("middle_name", models.CharField(max_length=40)),
                ("date_of_birth", models.DateField()),
            ],
            options={
                "db_table": "Patient",
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("diagnosis", models.CharField(max_length=200)),
                (
                    "recommendation",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200), size=None
                    ),
                ),
                ("date_of_visit", models.DateField()),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.doctor"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.patient"
                    ),
                ),
            ],
            options={
                "db_table": "Visit",
            },
        ),
        migrations.CreateModel(
            name="MedicalCard",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("visit_date", models.DateField()),
                (
                    "diagnosis",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200), size=None
                    ),
                ),
                ("current_condition", models.CharField(max_length=100)),
                (
                    "recommendations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200), size=None
                    ),
                ),
                ("payment", models.CharField(max_length=40)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.doctor"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.patient"
                    ),
                ),
            ],
            options={
                "db_table": "MedicalCard",
            },
        ),
        migrations.CreateModel(
            name="ClinicRoom",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("room_number", models.BigIntegerField(unique=True)),
                (
                    "working_days",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200), size=None
                    ),
                ),
                ("internal_phone_number", models.CharField(max_length=40)),
                (
                    "responsible_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="base.doctor"
                    ),
                ),
            ],
            options={
                "db_table": "ClinicRoom",
            },
        ),
    ]
