# Generated by Django 4.2.6 on 2023-12-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicalcard",
            name="payment",
        ),
        migrations.AddField(
            model_name="medicalcard",
            name="visits",
            field=models.ManyToManyField(related_name="MedicalCards", to="base.visit"),
        ),
        migrations.AddField(
            model_name="visit",
            name="payment",
            field=models.IntegerField(default=0),
        ),
    ]
