# Generated by Django 4.2.6 on 2023-12-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_remove_medicalcard_payment_medicalcard_visits_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="phone_number",
            field=models.CharField(default=89955991820, max_length=40),
        ),
    ]
